### ISSUE TITLE
Issues with removing the formatting of a url?

### ISSUE THREAD

**Issue by manasdk** [slackhq/hubot-slack#213] opened 2015-07-15 22:37 UTC
user types : `run local "ping test.hostname.com"`
bot receives : `run local "ping http://test.hostname.com"`

Looks like the rawMessage sent to the removeFormatting function(https://github.com/slackhq/hubot-slack/blob/master/src/slack.coffee#L153) was `run local “ping <http://test.hostname.com|test.hostname.com>"` 

Presumably due to the code https://github.com/slackhq/hubot-slack/blob/master/src/slack.coffee#L188 the link is returned instead of the label. Ordinarily this seems correct expect that the original user typed value has meaning and received value with a prefix of `http://` is incorrect. 

Looking at the docs https://api.slack.com/docs/formatting it seems like in this particular case it would make sense to return what the code characterizes as label? In this case it is impossible to deal with this upstream with know the user intent therefore the plea to fix it in hubot-slack.

The relevant test is https://github.com/slackhq/hubot-slack/blob/master/test/slack.coffee#L71

**Comment by technicalpickles** [comment] 2015-09-26 19:58
This is a tough one.  From https://api.slack.com/docs/formatting

> URL detection is performed by the server. We do this so that URL detection (a non-trivial operation) is performed consistently across multiple clients.

That means a client sends a hostname, Slack processes that as a URL, and that's what hubot sees. You can't really know what the user intended to send to the server, just that it's a link.

Hubot tends to deal in just plain text, so I could see a case for changing it to return the label rather than URL. But, there's scripts & hubots out in the wild that could be depending on this behavior.

**Comment by technicalpickles** [comment] 2015-09-27 04:08
Actually, this looks like a duplicate of https://github.com/slackhq/hubot-slack/issues/181

**Comment by technicalpickles** [comment] 2015-10-20 22:15
Closing as duplicate of #181

**Closed by technicalpickles** 2015-10-20 22:15 UTC
Labels: duplicate
