### ISSUE TITLE
hubot-slack does not honor bot names set in slack

### ISSUE THREAD

**Issue by ArcticSnowman** [slackhq/hubot-slack#327] opened 2016-07-25 19:20 UTC
* [X] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
bot created with this hubot-slack do not honor the name defined for the slack integration.  The bot reads its own message as the wrong ID, which break the ignored users.

### Expected result:
Message appearing in slack with the name/icon defined for the integration

### Actual result:
Message appearing in slack with default 'hubot' name and icon

### Attachments:
![image](https://cloud.githubusercontent.com/assets/13837922/17113966/e215ee3c-527a-11e6-994d-4d8142feac37.png)

    [Mon Jul 25 2016 15:14:16 GMT-0400 (EDT)] DEBUG Received message: '@steven.arnott: <factoid>? - Same as ~<factoid> except for there is no response if not found
    ...
    bender set jira_lookup_style [long|short]
    bender shoot target (in the legs/head/body) - Fires a foam dart at the target' in channel: archietest, from: hubot

**Comment by ArcticSnowman** [comment] 2016-07-25 19:23
Ok  this also covers it: #325

**Comment by ArcticSnowman** [comment] 2016-07-25 19:54
simple `msg.send <text>` works for honoring the name.

**Comment by DEGoodmanWilson** [comment] 2016-07-25 19:58
I'm going to close this as a duplicate of #325

**Closed by DEGoodmanWilson** 2016-07-25 19:58 UTC
