### ISSUE TITLE
Support for as_user=true in msg.send

### ISSUE THREAD

**Issue by spacediver** [slackhq/hubot-slack#325] opened 2016-07-20 23:47 UTC
Reporting from [here](https://github.com/slackhq/hubot-slack/issues/170#issuecomment-233676226), it seems that 
```
msg.send({
    attachments: [{
        title: 'a title',
        fallback: 'a fallback',
        title_link: 'http://example.com',
    }],
    username: process.env.HUBOT_SLACK_BOTNAME,
    as_user: true,
});
```
ignores `as_user`, and appears at Slack just like if it was:
```
msg.send({
    attachments: [{
        title: 'a title',
        fallback: 'a fallback',
        title_link: 'http://example.com',
    }],
    username: process.env.HUBOT_SLACK_BOTNAME,
});
```

BTW, is this a correct way to send attachments these days, via v3?

**Comment by spacediver** [comment] 2016-07-20 23:50
@DEGoodmanWilson, do you probably have any idea of where to look for this (node-slack-sdk perhaps?), or how else to ensure `as_user` is passed as `true`? Thanks in advance!

**Comment by DEGoodmanWilson** [comment] 2016-07-20 23:51
Will be investigating! And yes, that is the way to do attachments ;)

**Comment by spacediver** [comment] 2016-07-21 09:46
Do you know a quickfix, so that I could solve my itch right away? Like calling slack adapter directly, etc. Thanks in advance!

**Comment by DEGoodmanWilson** [comment] 2016-07-21 15:35
That's all we really do, actually. I suspect the problem is in the Slack SDK layer just below the Hubot adapter.

**Comment by ArcticSnowman** [comment] 2016-07-25 19:26
`as_user: true` should be the default, according to the slack docs.  if your wanting to override the name defined in slack, it should be `as_user: false`.  Should it not?

**Comment by spacediver** [comment] 2016-07-25 19:43
[Here](https://api.slack.com/methods/chat.postMessage) I see that `as_user` Defaults to false (not to confuse with example value in the second column of the table).

**Comment by ArcticSnowman** [comment] 2016-07-25 19:48
@spacediver  - Your correct... that tables a little confusing..

**Comment by ArcticSnowman** [comment] 2016-07-25 19:58
`msg.send <simple text>` does correctly use the right user, so slack must infer the right `as_user`

**Comment by ArcticSnowman** [comment] 2016-07-25 20:56
> If as_user is not provided at all, then the value is inferred, based on the scopes granted to the caller: If the caller could post with as_user passed as false, then that is how the method behaves; otherwise, the method behaves as if as_user were passed as true.

Prior to 4.0, the code explicitly added as_user=true.  

    if data.username && data.username != @robot.name
      msg.as_user = false
      msg.username = data.username
      if data.icon_url?
        msg.icon_url = data.icon_url
      else if data.icon_emoji?
        msg.icon_emoji = data.icon_emoji
    else
      msg.as_user = true

**Comment by spacediver** [comment] 2016-07-25 21:01
@ArcticSnowman yes, simple text messages are no problem, these are displayed correctly. It is rich messages (with attachments) that are seemingly processed as if `as_user=false`.

**Comment by ArcticSnowman** [comment] 2016-07-25 21:03
Also prior to 4.0, the hubot-slack JSON'ifed the attachment prior to passing to the slack-client.  Not sure that matter here or not.

**Comment by DEGoodmanWilson** [comment] 2016-07-26 14:29
Thanks for the additional data y'all. The new version of `node-slack-sdk` doesn't require JSONifying the message, which is why that change. I'll look into the other difference that was brought up. I have to admit that I am snowed under this week, so it might be a little time before I can properly dig on this. Just wanted to let you know you're not being ignored.

**Comment by ArcticSnowman** [comment] 2016-07-26 15:38
@DEGoodmanWilson    I going to try building the message object explicitly rather than pass it in implicitly to `msg.send`  to see if that works.

**Comment by DEGoodmanWilson** [comment] 2016-07-26 15:57
Just wanted to reference that #329 is a duplicate that has some nice clarifying information on this issue.

**Comment by ArcticSnowman** [comment] 2016-07-26 20:58
@DEGoodmanWilson    I tried constructing the message as a object and add the as_user, similar to the way 3.x added it in the customMessage.  But that made no difference.

**Comment by spacediver** [comment] 2016-08-01 13:09
Hey folks, can we come up with a quick fix for that? Any working solution will suffice =) Thanks!

**Comment by ArcticSnowman** [comment] 2016-08-01 13:16
@spacediver   The only 'quick fix' that I know of is to revert to pre-4.0....  It looks like there is something in `@slack|client` that is at fault..   need some way to capture the HTTP/JSON request it sends to slack to see why explicitly setting `as_user=true` does not work.

**Comment by DEGoodmanWilson** [comment] 2016-08-01 14:27
Been digging. The `as_user` worries seem a red herring. The problem is, rather, that messages sent via `chat.postMessage` are being sent as though `as_user=false`, when in fact the default is `true`. Something is inserting `as_user=false` unless it gets overridden explicitly. Just adding this here as notes while I dig.

**Comment by DEGoodmanWilson** [comment] 2016-08-01 15:22
Been digging all morning. This is a toughie, y'all.

**Closed** 2016-08-02 15:48 UTC
Labels: bug, Priority—High

**Comment by spacediver** [comment] 2016-08-02 16:44
The fIx works, thanks a lot!
