### ISSUE TITLE
Make hubot's message only visible to the user who asked it

### ISSUE THREAD

**Issue by hoodwink73** [slackhq/hubot-slack#221] opened 2015-08-26 20:20 UTC
There are some slack commands(/asana) which uses slackbot to answer back. This has the added benefit of the answer not visible by anyone but the user who asked the question.

Can Hubot do sort of a similar thing?

**Comment by jeffbyrnes** [comment] 2015-08-27 13:43
Ooh! This would be _super_ cool.

**Comment by technicalpickles** [comment] 2015-09-26 19:42
cc https://github.com/slackhq/hubot-slack/issues/223 for implementing Slash commands for hubot. Those are returned only to the user currently.

I don't know of any way for the API to return messages private to the user that aren't DMs, like /asana or Slash commands. So, Slack would need to implement something like that first.

That said, one confusing thing is you'd have to say a command in a room. Everyone in the room would see it, and only hubot would respond privately.

Actually, the more I think about it, https://github.com/slackhq/hubot-slack/issues/223 is a duplicate of this. I think what's being asked here is slash commands.

**Comment by DEGoodmanWilson** [comment] 2016-06-27 19:42
Slash command responses can be marked as ephemeral (viewable to only the user who invoked the command) or public (viewable to everyone). But, you can't send responses as Slackbot. (Asana was a special snowflake Slack wrote themselves.)

Marking as a duplicate of #223 and closing.

**Closed by DEGoodmanWilson** 2016-06-27 19:42 UTC
Labels: duplicate
