### ISSUE TITLE
Hubot appears as user, but is offline

### ISSUE THREAD

**Issue by jglovier** [slackhq/hubot-slack#161] opened 2015-03-06 17:59 UTC
I've installed Hubot in a new Slack instance via the Hubot Integration + @cobyism's https://github.com/cobyism/hubot-heroku-slack deploy button.

Everything looks normal on the Heroku side, and in the Hubot integration side, except Hubot is showing up as an offline user.

![image](https://cloud.githubusercontent.com/assets/1319791/6530627/7342deca-c400-11e4-9af4-47bc3fd6d15c.png)

The last time I setup a Hubot for Slack, I didn't use the deploy to Heroku button (not sure if that makes a difference), and Hubot is working in that Slack instance, but doesn't show up as a user.

I can't find any further configurations to change to troubleshoot any further. Any ideas? 

:bulb: :grey_question:

**Comment by evansolomon** [comment] 2015-03-06 18:36
This usually happens because Heroku dynos idle/sleep/whatever after some period of inactivity on free plans https://devcenter.heroku.com/articles/dynos#dyno-sleeping

Assuming that's what's happening there are a couple ways to deal with it, most people use https://github.com/hubot-scripts/hubot-heroku-keepalive

**Comment by jglovier** [comment] 2015-03-06 19:31
@evansolomon but the logs show he does appear to be getting the keep alive pings:

```
2015-03-06T17:16:27.421159+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=55737c73-0f42-46b3-afe6-fa4b727b13ad fwd="54.92.158.223" dyno=web.1 connect=1ms service=2ms status=200 bytes=144
2015-03-06T17:16:27.421902+00:00 app[web.1]: [Fri Mar 06 2015 17:16:27 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-06T17:21:27.407434+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=f3632045-7353-4c84-bf6c-5ebe94e5ec3b fwd="54.92.158.223" dyno=web.1 connect=1ms service=2ms status=200 bytes=144
2015-03-06T17:21:27.413191+00:00 app[web.1]: [Fri Mar 06 2015 17:21:27 GMT+0000 (UTC)] INFO keep alive ping!
```

**Comment by jglovier** [comment] 2015-03-06 19:32
Also, this was right after deploying him. I.e. there was never a period where he has been active in there yet.

**Comment by evansolomon** [comment] 2015-03-06 19:35
> there was never a period where he has been active in there yet

Oh, I see.  In that case I would guess it's a code/configuration problem.  Maybe the wrong or missing API key?

**Comment by jglovier** [comment] 2015-03-06 19:59
>Maybe the wrong or missing API key?

Well I've checked and double checked the API key. I even regenerated it in Slack and updated it in Heroku to make sure.

**Comment by evansolomon** [comment] 2015-03-06 20:10
Do you get any logs about the slack client connecting/crashing/etc?

**Comment by jglovier** [comment] 2015-03-09 17:05
@evansolomon no, doesn't appear to be any like that:

```
|===jglovier===| ~/github/hubot.github.com $ heroku logs --app circles-slack-hubot
2015-03-09T12:49:14.528691+00:00 app[web.1]: [Mon Mar 09 2015 12:49:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T12:54:14.531809+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=dee549e3-e8c1-4624-8486-44cb142e4f7c fwd="54.158.79.124" dyno=web.1 connect=1ms service=3ms status=200 bytes=144
2015-03-09T12:54:14.532730+00:00 app[web.1]: [Mon Mar 09 2015 12:54:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T12:59:14.558119+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=f01cdf9e-22e8-49e4-8118-2a76fa903aae fwd="54.158.79.124" dyno=web.1 connect=1ms service=5ms status=200 bytes=144
2015-03-09T12:59:14.559254+00:00 app[web.1]: [Mon Mar 09 2015 12:59:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T13:04:14.547477+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=9e4b040a-b932-456f-9798-2c905f4f05c6 fwd="54.158.79.124" dyno=web.1 connect=1ms service=8ms status=200 bytes=144
2015-03-09T13:04:14.544751+00:00 app[web.1]: [Mon Mar 09 2015 13:04:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T13:09:14.545656+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=b1e4a460-34ed-4272-973c-b47be7a7b45c fwd="54.158.79.124" dyno=web.1 connect=2ms service=2ms status=200 bytes=144
2015-03-09T13:09:14.546395+00:00 app[web.1]: [Mon Mar 09 2015 13:09:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T13:14:14.545330+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=41f2235d-b660-42ac-a3ef-4c476484a1aa fwd="54.158.79.124" dyno=web.1 connect=1ms service=2ms status=200 bytes=144
2015-03-09T13:14:14.545986+00:00 app[web.1]: [Mon Mar 09 2015 13:14:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T13:19:14.563649+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=6f62ec9b-e525-4782-8642-f7728d1d87db fwd="54.158.79.124" dyno=web.1 connect=1ms service=4ms status=200 bytes=144
2015-03-09T13:19:14.566056+00:00 app[web.1]: [Mon Mar 09 2015 13:19:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T13:24:14.560667+00:00 app[web.1]: [Mon Mar 09 2015 13:24:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T13:24:14.561768+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=92ef8033-644d-4896-822c-56b767c054b0 fwd="54.158.79.124" dyno=web.1 connect=1ms service=3ms status=200 bytes=144
2015-03-09T13:29:14.577676+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=9b4a7825-60f6-4e46-aa84-88db53e6b801 fwd="54.158.79.124" dyno=web.1 connect=1ms service=1ms status=200 bytes=144
2015-03-09T13:29:14.576961+00:00 app[web.1]: [Mon Mar 09 2015 13:29:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T13:34:14.563419+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=ef935c64-8210-4f17-aeac-ed431357a7f4 fwd="54.158.79.124" dyno=web.1 connect=2ms service=2ms status=200 bytes=144
2015-03-09T13:34:14.563736+00:00 app[web.1]: [Mon Mar 09 2015 13:34:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T13:39:14.570654+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=5f8e2f7b-38bb-4a3b-a83e-0f94ae3dc0d7 fwd="54.158.79.124" dyno=web.1 connect=4ms service=4ms status=200 bytes=144
2015-03-09T13:39:14.572289+00:00 app[web.1]: [Mon Mar 09 2015 13:39:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T13:44:14.618791+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=9a0431a1-daa9-491b-9617-1be57fd5870b fwd="54.158.79.124" dyno=web.1 connect=1ms service=2ms status=200 bytes=144
2015-03-09T13:44:14.620264+00:00 app[web.1]: [Mon Mar 09 2015 13:44:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T13:49:14.575408+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=89188092-b1ca-4893-9160-3615ba0c3c59 fwd="54.158.79.124" dyno=web.1 connect=1ms service=3ms status=200 bytes=144
2015-03-09T13:49:14.577454+00:00 app[web.1]: [Mon Mar 09 2015 13:49:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T13:54:14.578884+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=7a5cafde-5979-41d0-baac-be9ba4159e62 fwd="54.158.79.124" dyno=web.1 connect=2ms service=3ms status=200 bytes=144
2015-03-09T13:54:14.579918+00:00 app[web.1]: [Mon Mar 09 2015 13:54:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T13:59:14.594525+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=b47885b2-a2de-40e1-9d1f-fb26bdb56c8f fwd="54.158.79.124" dyno=web.1 connect=6ms service=3ms status=200 bytes=144
2015-03-09T13:59:14.599580+00:00 app[web.1]: [Mon Mar 09 2015 13:59:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T14:04:14.578958+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=9a5eefee-0540-4233-bc78-706e85447c42 fwd="54.158.79.124" dyno=web.1 connect=0ms service=2ms status=200 bytes=144
2015-03-09T14:04:14.578114+00:00 app[web.1]: [Mon Mar 09 2015 14:04:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T14:09:14.620623+00:00 app[web.1]: [Mon Mar 09 2015 14:09:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T14:09:14.622380+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=016a7b01-5fe9-40df-ac22-fa50ddbdbd1f fwd="54.158.79.124" dyno=web.1 connect=17ms service=17ms status=200 bytes=144
2015-03-09T14:14:14.582999+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=cd20ea98-78fe-41ef-be86-2c2ebcc4be67 fwd="54.158.79.124" dyno=web.1 connect=2ms service=2ms status=200 bytes=144
2015-03-09T14:14:14.583764+00:00 app[web.1]: [Mon Mar 09 2015 14:14:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T14:19:14.604551+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=698e31e2-cef3-4370-a524-7c8e38d9c4a0 fwd="54.158.79.124" dyno=web.1 connect=1ms service=3ms status=200 bytes=144
2015-03-09T14:19:14.607701+00:00 app[web.1]: [Mon Mar 09 2015 14:19:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T14:24:14.596026+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=698aca08-5ef4-4661-9aa8-4137142a38fd fwd="54.158.79.124" dyno=web.1 connect=1ms service=6ms status=200 bytes=144
2015-03-09T14:24:14.595689+00:00 app[web.1]: [Mon Mar 09 2015 14:24:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T14:29:14.615832+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=4a825704-cd72-4369-a800-fb41b9f74a65 fwd="54.158.79.124" dyno=web.1 connect=7ms service=19ms status=200 bytes=144
2015-03-09T14:29:14.616269+00:00 app[web.1]: [Mon Mar 09 2015 14:29:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T14:34:14.589864+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=40b3f207-d6ab-455e-9c1c-de5efedd0fab fwd="54.158.79.124" dyno=web.1 connect=0ms service=1ms status=200 bytes=144
2015-03-09T14:34:14.591022+00:00 app[web.1]: [Mon Mar 09 2015 14:34:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T14:39:14.601592+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=8ba7d134-797d-494a-b9d5-0ea3695b74e6 fwd="54.158.79.124" dyno=web.1 connect=1ms service=2ms status=200 bytes=144
2015-03-09T14:39:14.601505+00:00 app[web.1]: [Mon Mar 09 2015 14:39:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T14:44:14.601528+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=2a63d93d-5028-451e-841f-9c2ec8cc8aa0 fwd="54.158.79.124" dyno=web.1 connect=1ms service=3ms status=200 bytes=144
2015-03-09T14:44:14.601374+00:00 app[web.1]: [Mon Mar 09 2015 14:44:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T14:49:14.595643+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=dca243dc-517f-48d4-9e29-427b277c4f42 fwd="54.158.79.124" dyno=web.1 connect=0ms service=1ms status=200 bytes=144
2015-03-09T14:49:14.599810+00:00 app[web.1]: [Mon Mar 09 2015 14:49:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T14:54:14.601012+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=1cfb9c2e-9b73-44b1-9f74-402c7f93ad52 fwd="54.158.79.124" dyno=web.1 connect=1ms service=1ms status=200 bytes=144
2015-03-09T14:54:14.602256+00:00 app[web.1]: [Mon Mar 09 2015 14:54:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T14:59:14.627507+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=db4167b6-8934-4355-978f-5d02b2c7c6e5 fwd="54.158.79.124" dyno=web.1 connect=4ms service=6ms status=200 bytes=144
2015-03-09T14:59:14.629378+00:00 app[web.1]: [Mon Mar 09 2015 14:59:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T15:04:14.631824+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=38308484-e967-4b98-b2b1-71f7cba4ecd6 fwd="54.158.79.124" dyno=web.1 connect=7ms service=1ms status=200 bytes=144
2015-03-09T15:04:14.631185+00:00 app[web.1]: [Mon Mar 09 2015 15:04:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T15:09:14.660729+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=54569c9c-36cd-409b-8b50-49faffef1bbb fwd="54.158.79.124" dyno=web.1 connect=7ms service=4ms status=200 bytes=144
2015-03-09T15:09:14.664552+00:00 app[web.1]: [Mon Mar 09 2015 15:09:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T15:14:14.620462+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=16c9b1f5-489b-4231-a968-591ae23b26af fwd="54.158.79.124" dyno=web.1 connect=2ms service=1ms status=200 bytes=144
2015-03-09T15:14:14.623562+00:00 app[web.1]: [Mon Mar 09 2015 15:14:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T15:19:14.635316+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=14dea8cc-6f9a-491b-a945-a4864656c683 fwd="54.158.79.124" dyno=web.1 connect=1ms service=2ms status=200 bytes=144
2015-03-09T15:19:14.638590+00:00 app[web.1]: [Mon Mar 09 2015 15:19:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T15:24:14.633851+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=aed94ba9-487b-4aff-beed-78d3959189ef fwd="54.158.79.124" dyno=web.1 connect=2ms service=3ms status=200 bytes=144
2015-03-09T15:24:14.634332+00:00 app[web.1]: [Mon Mar 09 2015 15:24:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T15:29:14.629974+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=84c7ac8b-51cb-40bc-b33a-c878e0c122d7 fwd="54.158.79.124" dyno=web.1 connect=1ms service=3ms status=200 bytes=144
2015-03-09T15:29:14.630704+00:00 app[web.1]: [Mon Mar 09 2015 15:29:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T15:34:14.832616+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=e082b429-e9b6-4e56-a60c-dc695a59b7e6 fwd="54.158.79.124" dyno=web.1 connect=2ms service=2ms status=200 bytes=144
2015-03-09T15:34:14.834790+00:00 app[web.1]: [Mon Mar 09 2015 15:34:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T15:39:14.661134+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=40248b10-9a78-4d83-8a8f-1fedfe101fcc fwd="54.158.79.124" dyno=web.1 connect=18ms service=3ms status=200 bytes=144
2015-03-09T15:39:14.662499+00:00 app[web.1]: [Mon Mar 09 2015 15:39:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T15:44:14.675757+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=e3c5f715-3d16-4f28-86ac-109d4f8064e1 fwd="54.158.79.124" dyno=web.1 connect=3ms service=3ms status=200 bytes=144
2015-03-09T15:44:14.678532+00:00 app[web.1]: [Mon Mar 09 2015 15:44:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T15:49:14.778261+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=ba645881-02df-4461-8cab-2622a24fa043 fwd="54.158.79.124" dyno=web.1 connect=11ms service=33ms status=200 bytes=144
2015-03-09T15:49:14.781477+00:00 app[web.1]: [Mon Mar 09 2015 15:49:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T15:54:14.645401+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=8358edb4-70b3-403a-bb55-a8338fb49ecb fwd="54.158.79.124" dyno=web.1 connect=1ms service=1ms status=200 bytes=144
2015-03-09T15:54:14.649007+00:00 app[web.1]: [Mon Mar 09 2015 15:54:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T15:59:14.654804+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=db628cd6-72ce-4855-bf4d-4ed6b94dba35 fwd="54.158.79.124" dyno=web.1 connect=1ms service=2ms status=200 bytes=144
2015-03-09T15:59:14.657257+00:00 app[web.1]: [Mon Mar 09 2015 15:59:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T16:04:14.654345+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=a9702beb-bcd9-460a-950f-fcb1eb27c58c fwd="54.158.79.124" dyno=web.1 connect=2ms service=3ms status=200 bytes=144
2015-03-09T16:04:14.656195+00:00 app[web.1]: [Mon Mar 09 2015 16:04:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T16:09:14.703207+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=8419d015-0970-4a3e-999e-a1c36f529d4e fwd="54.158.79.124" dyno=web.1 connect=9ms service=4ms status=200 bytes=144
2015-03-09T16:09:14.706505+00:00 app[web.1]: [Mon Mar 09 2015 16:09:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T16:14:14.764064+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=e738a03c-90e3-4cd8-9eca-144f4a335011 fwd="54.158.79.124" dyno=web.1 connect=7ms service=18ms status=200 bytes=144
2015-03-09T16:14:14.766850+00:00 app[web.1]: [Mon Mar 09 2015 16:14:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T16:19:14.660434+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=fabb5b33-b366-4022-8dc4-7eed3ca1f0f4 fwd="54.158.79.124" dyno=web.1 connect=1ms service=1ms status=200 bytes=144
2015-03-09T16:19:14.661959+00:00 app[web.1]: [Mon Mar 09 2015 16:19:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T16:24:14.674197+00:00 app[web.1]: [Mon Mar 09 2015 16:24:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T16:24:14.661543+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=3b26c079-7e16-4839-a64c-ff19f037bba4 fwd="54.158.79.124" dyno=web.1 connect=2ms service=1ms status=200 bytes=144
2015-03-09T16:29:14.704821+00:00 heroku[router]: at=info method=POST path="/hub
ot/ping" host=circles-slack-hubot.herokuapp.com request_id=a040104f-e5a0-4957-82d2-f82d652fa66f fwd="54.158.79.124" dyno=web.1 connect=2ms service=4ms status=200 bytes=144
2015-03-09T16:29:14.708097+00:00 app[web.1]: [Mon Mar 09 2015 16:29:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T16:34:14.685918+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=65fd6201-ceaf-4229-821e-38fc55b7d089 fwd="54.158.79.124" dyno=web.1 connect=4ms service=9ms status=200 bytes=144
2015-03-09T16:34:14.682008+00:00 app[web.1]: [Mon Mar 09 2015 16:34:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T16:39:14.695901+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=e6047775-a8a4-48b5-91a3-a629f7d16cf4 fwd="54.158.79.124" dyno=web.1 connect=15ms service=5ms status=200 bytes=144
2015-03-09T16:39:14.696461+00:00 app[web.1]: [Mon Mar 09 2015 16:39:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T16:44:14.682820+00:00 app[web.1]: [Mon Mar 09 2015 16:44:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T16:44:14.690492+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=54ccc771-590c-43d6-b6db-11bf56c7435b fwd="54.158.79.124" dyno=web.1 connect=5ms service=9ms status=200 bytes=144
2015-03-09T16:49:14.810125+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=49981888-5679-4a30-b8d2-f546cf02620f fwd="54.158.79.124" dyno=web.1 connect=21ms service=41ms status=200 bytes=144
2015-03-09T16:49:14.812209+00:00 app[web.1]: [Mon Mar 09 2015 16:49:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T16:54:14.667139+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=fcab1587-b101-42ca-9312-702c1ae461ac fwd="54.158.79.124" dyno=web.1 connect=1ms service=2ms status=200 bytes=144
2015-03-09T16:54:14.669765+00:00 app[web.1]: [Mon Mar 09 2015 16:54:14 GMT+0000 (UTC)] INFO keep alive ping!
2015-03-09T16:59:14.731317+00:00 heroku[router]: at=info method=POST path="/hubot/ping" host=circles-slack-hubot.herokuapp.com request_id=0c88a9fb-c6b1-4b06-aeee-a8a3e82e2d99 fwd="54.158.79.124" dyno=web.1 connect=13ms service=21ms status=200 bytes=144
2015-03-09T16:59:14.734022+00:00 app[web.1]: [Mon Mar 09 2015 16:59:14 GMT+0000 (UTC)] INFO keep alive ping!
```

**Comment by evansolomon** [comment] 2015-03-09 18:16
Can you run it locally?  Is there a minimum test case you can reproduce the problem with?  In particular, it seems valuable to figure out if this is a problem in the code or a problem in the deploy/configuration.

**Comment by parkr** [comment] 2015-03-26 19:38
We have to restart hubot often as well. It seems like Slack invalidates the access token, or just stops sending input/accepting responses.

**Comment by evansolomon** [comment] 2015-03-27 19:43
> It seems like Slack invalidates the access token, or just stops sending input/accepting responses

Do you have any logs/data/etc from this happening?

**Comment by parkr** [comment] 2015-03-27 20:08
> Do you have any logs/data/etc from this happening?

No.

**Comment by evansolomon** [comment] 2015-03-27 20:16
Okay.  I am pretty sure Slack does not invalidate tokens proactively.  As for "stops sending input/accepting responses" it seem like that could be a symptom of a few different problems rather than something Slack does intentionally.  For example, if the process crashes and isn't restarted it would sort of behave that way (and would also show up as offline).

**Comment by parkr** [comment] 2015-03-27 20:34
Ok, I'll keep an eye out for it and post back.

**Comment by jglovier** [comment] 2015-03-30 19:25
Forgive my ignorance, but how do I trigger a restart of the app on Heroku?

**Comment by evansolomon** [comment] 2015-03-30 20:09
https://devcenter.heroku.com/articles/application-offline#restart-your-application

**Comment by jglovier** [comment] 2015-03-30 21:03
@evansolomon thanks!

Yeah that didn't appear to work. Hubot still appears as offline in Slack, and doesn't respond to pings.

![image](https://cloud.githubusercontent.com/assets/1319791/6906732/91df0adc-d6fe-11e4-90b9-8bdcf7907e73.png)

**Comment by evansolomon** [comment] 2015-03-30 21:30
Can you run it locally?

**Comment by rteslaru** [comment] 2015-03-30 22:19
Having the exact same issue with Hubot integration via http://chato.ps

**Comment by jglovier** [comment] 2015-03-30 22:53
>Can you run it locally?

@evansolomon yup - running fine locally

**Comment by jglovier** [comment] 2015-03-30 22:56
Worth noting is that in the other Slack room where he is successfully working, he does not appear as a user, but simply responds when you type `hubot <command>`

**Comment by evansolomon** [comment] 2015-03-30 23:23
If it's working locally then it sounds like the problem is in the heroku config/deployment/something.  Unfortunately I don't use Heroku much so I can't be super helpful there.

> in the other Slack room where he is successfully working, he does not appear as a user, but simply responds when you type hubot <command>

Are you possibly using the old hubot integration? https://github.com/slackhq/hubot-slack#upgrading-from-earlier-versions-of-hubot

**Comment by evansolomon** [comment] 2015-03-31 00:47
@rteslaru I don't really know what chato.ps is/how it works. Can you add some context on that?

**Comment by jglovier** [comment] 2015-03-31 13:31
>Are you possibly using the old hubot integration? https://github.com/slackhq/hubot-slack#upgrading-from-earlier-versions-of-hubot

Hmm, not sure. I just used @cobyism's [deploy to Heroku button](https://github.com/cobyism/hubot-heroku-slack#hubot-on-heroku-with-the-slack-adaptor). Maybe that's using the older integration? I'll try the upgrade instructions and see if that works.

**Comment by jglovier** [comment] 2015-03-31 14:14
I tried upgrading and redeploying but still not responding. :confused:

**Comment by pklapperich** [comment] 2015-06-11 17:18
@jglovier The bot will show up as offline as soon as you create and enable the hubot integration. So that it shows as offline indicates that your hubot is not talking to slack. Maybe it's not running?

2nd, The hubot-heroku-slack repository hasn't had a commit since Nov 2014. It's probably out of date. I tried it myself just now and had the same issue that you did. When I used "heroku git:clone" to pull down a copy of what the button deployed to my heroku account, it does not run locally with the slack adapter (I get an error HUBOT_AUTH_ADMIN environment variable not set and my Hubot user remains offline). You should probably post an issue in @cobyism's repo as it's clear to me his button doesn't work.

Here's how I got my hubot [deployed to heroku](https://github.com/slackhq/hubot-slack/issues/199#issuecomment-111190827) by using this repo hubot-slack.

**Comment by jglovier** [comment] 2015-06-15 21:24
>The hubot-heroku-slack repository hasn't had a commit since Nov 2014. It's probably out of date. I tried it myself just now and had the same issue that you did.

@pklapperich yeah that's a good point. I'll have to set it up the old way. Thx. :tophat:

**Comment by LucasKA** [comment] 2015-06-20 00:39
I'm having this exact same issue, even though I configured a hubot the same way for a different channel, less than a week ago. The first integration is running perfectly. The new one only connects to slack if I run it locally.

All configs are the same.

I think something has changed in heroic. :/

@jglovier What is the "old way"?

**Comment by jglovier** [comment] 2015-06-20 01:59
>@jglovier What is the "old way"?

@LucasKA via the traditional docs method of manually setting up hubot locally, then adding to Heroku and deploying all manually. I.e.: https://hubot.github.com/docs/#getting-started-with-hubot

**Comment by eriklindebratt** [comment] 2015-06-22 16:11
I'm experiencing the exact same issue but instead of Heroku I'm running Hubot on a Google Compute Engine instance.

**Comment by LucasKA** [comment] 2015-06-25 23:38
@jglovier Oh no, that's not going to work, that's how I set mine up. (I didn't see you used the deploy button)

**Comment by pklapperich** [comment] 2015-06-26 01:27
@LucasKA you said it works locally but not after you "git push heroku master", right? Did you commit everything? Check .gitignore and make sure you aren't ignoring your node_modules folder. If you are, you might have to "git add" node_modules/hubot-slack and any other folders you have setup in external_scripts.js but haven't committed.

**Comment by LucasKA** [comment] 2015-06-26 04:21
@pklapperich Nice call, I'll try it, I am ignoring my node_modules folder, but that doesn't explain why my other hubot works perfectly with the same setup. (node_modules ignored there too)

**Comment by LucasKA** [comment] 2015-06-26 04:35
These are my heroku logs:

```2015-06-26T04:23:06.852202+00:00 heroku[slug-compiler]: Slug compilation started
2015-06-26T04:23:06.852233+00:00 heroku[slug-compiler]: Slug compilation finished
2015-06-26T04:23:07.008513+00:00 heroku[web.1]: State changed from up to starting
2015-06-26T04:23:08.704084+00:00 heroku[web.1]: Starting process with command `bin/hubot -a slack`
2015-06-26T04:23:10.089399+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2015-06-26T04:23:10.137343+00:00 app[web.1]: Detected 512 MB available memory, 512 MB limit per process (WEB_MEMORY)
2015-06-26T04:23:10.137365+00:00 app[web.1]: Recommending WEB_CONCURRENCY=1
2015-06-26T04:23:12.196138+00:00 heroku[web.1]: Process exited with status 0
2015-06-26T04:23:12.365573+00:00 app[web.1]: [Fri Jun 26 2015 04:23:12 GMT+0000 (UTC)] ERROR No services token provided to Hubot```

Weird thing is that even scaling it up and setting WEB_CONCURRENCY to 1 does nothing.

**Comment by pklapperich** [comment] 2015-06-26 21:17
>2015-06-26T04:23:12.365573+00:00 app[web.1]: [Fri Jun 26 2015 04:23:12 GMT+0000 (UTC)] ERROR No services token provided to Hubot

Check your environment variables? I think that error means you haven't set "HUBOT_SLACK_TOKEN"

**Comment by LucasKA** [comment] 2015-06-26 21:37
It was set, I had checked that, but I just did a fresh setup (like 15 min overall), and it's working now.

¯\_(ツ)_/¯

**Comment by dylanh724** [comment] 2015-11-04 14:33
I still have this issue -- I tried fresh setup and still not working.

**Comment by AlliVaughn** [comment] 2015-12-04 19:40
@pklapperich Thanks for the solution.  I had the same issue until you pointed out the  obvious.  Um, yes.  the  *entire* node_module folder was indeed in .gitignore because of the  generator.  My little tacobot works perfectly now!

**Comment by DEGoodmanWilson** [comment] 2016-06-29 20:51
Closing this as resolved…whew!

**Closed by DEGoodmanWilson** 2016-06-29 20:51 UTC
Labels: ready
