### ISSUE TITLE
Formating messages

### ISSUE THREAD

**Issue by marcuslindblom** [slackhq/hubot-slack#170] opened 2015-03-20 10:31 UTC
How can I format messages from my hubot scripts? This message: `msg.send "Foo <@U123> bar <http://slack.com>"` generates `Foo @U123 bar <http://slack.com>` when my hubot prints it to a channel? Are there any script example using more advanced formatting?

**Comment by errodr** [comment] 2015-03-20 13:38
Take a look at attachments: https://api.slack.com/docs/attachments

**Comment by marcuslindblom** [comment] 2015-03-20 14:00
@errodr Ok, but in my coffee script, how do I compose a message after `msg.send`?

```
module.exports = (robot) ->

  robot.respond /team (.*)$/i, (msg)->
    team = msg.match[1]
    query msg, "http://api.xxx.xx/#{team}"

  query = (msg, url) ->
    msg.http(url)
    .get() (err, res, body) ->
      data = JSON.parse(body)
      if err
        msg.send "Fail! Something went wrong. Couldn't start the build for some reason"
      else
        if data
          msg.send ""
        else
          msg.send "Fail..."
```

**Comment by errodr** [comment] 2015-03-20 16:52
Here is an example of what I used to send the attachment:

```
  sendMessage = (results, msg) ->
    robot.emit 'slack-attachment',
      message:
        room: msg.message.room
      content: results
```

You can see that a **slack-attachment** is emitted. The content (results) of that message is of the form:

```
{
  "fallback": "New ticket from Andrea Lee - Ticket #1943: Can't rest my password - https://groove.hq/path/to/ticket/1943",
  "pretext": "New ticket from Andrea Lee",
  "title": "Ticket #1943: Can't reset my password",
  "title_link": "https://groove.hq/path/to/ticket/1943",
  "text": "Help! I tried to reset my password but nothing happened!",
  "color": "#7CD197"
}
```

**Comment by marcuslindblom** [comment] 2015-03-23 17:07
@errodr `emit` does not send anything to slack. How can I use msg.send and format the message?

**Comment by yusufhm** [comment] 2015-06-18 01:17
@marcuslindblom were you able to find a solution for this?

**Comment by marcuslindblom** [comment] 2015-06-18 06:04
@yusufhm no, sorry, and I couldn't find any working example.

**Comment by yusufhm** [comment] 2015-06-18 23:16
@marcuslindblom I've been able to do it using the **customMessage()** method from the adapter (lines 254-281 in https://github.com/slackhq/hubot-slack/blob/master/src/slack.coffee). Here's how I used it:

```coffeescript
# create the message with attachment object
msgData = {
  channel: res.message.room
  text: "Latest changes"
  attachments: [
    {
      fallback: "Comparing #{latestRelease.name}...#{latestRelease.target_commitish} - #{compare.html_url}",
      title: "Comparing #{latestRelease.name}...#{latestRelease.target_commitish}"
      title_link: compare.html_url
      text: commits_summary
      mrkdwn_in: ["text"]
    }
  ]
}

# post the message
robot.adapter.customMessage msgData
```

Look at both the method code and the Attachment documentation somebody posted earlier and you should be able to do what you want.

**Comment by technicalpickles** [comment] 2015-09-27 04:06
This is a duplicate of https://github.com/slackhq/hubot-slack/issues/43 . I just posted a work around there, but basically it's like @yusufhm posted, you can send a customMessage to do it.

**Comment by DEGoodmanWilson** [comment] 2016-06-29 20:34
This is being resolved in v4. Closing for the time being.

**Closed by DEGoodmanWilson** 2016-06-29 20:34 UTC
Labels: duplicate, possibly fixed in hubot-slack v4

**Comment by CatTail** [comment] 2016-07-09 11:48
@DEGoodmanWilson When v4 will be released?

**Comment by spacediver** [comment] 2016-07-19 08:14
@CatTail v4 is out! 
@DEGoodmanWilson How do we send attachments in v4? Cannot find example easily. Thanks!

**Comment by DEGoodmanWilson** [comment] 2016-07-19 15:30
@spacediver It is easy: Just add fields to your message object, per the docs: https://api.slack.com/docs/message-attachments

**Comment by spacediver** [comment] 2016-07-19 15:42
@DEGoodmanWilson Should I do `msg.send` or `robot.emit`? I cannot google up useful examples. If i do
```            msg.send({
                attachments: [{
                    title: 'title',
                    fallback: 'title',
                    title_link: 'http://example.com',
                }],
                username: process.env.HUBOT_SLACK_BOTNAME,
            });```

It ends up displayed just like if `as_user` was [set to false](https://api.slack.com/methods/chat.postMessage#authorship). Adding `as_user: true` into object does not help.

How to do that right? 

Thanks.

**Comment by DEGoodmanWilson** [comment] 2016-07-19 15:44
Where are you adding `as_user` into the object? Just to verify?

**Comment by spacediver** [comment] 2016-07-19 15:46
like this:
```
msg.send({
    attachments: [{
        title: project.fields.name + ' task summary',
        fallback: project.fields.name + ' task summary',
        title_link: 'http://phab.messapps.com/project/view/' + project.id,
    }],
    username: process.env.HUBOT_SLACK_BOTNAME,
    as_user: true,
});
```

(sibling to `attachments`, parallel to documentation).

**Comment by DEGoodmanWilson** [comment] 2016-07-19 15:47
OK, that's a bug! Just wanted  to verify. Let's take this to a new issue?

**Comment by spacediver** [comment] 2016-07-19 15:48
Sure, thanks! Should be tested on `xoxb-` bot token.

**Comment by p00j4** [comment] 2018-01-12 10:10
I'm trying to pass attachment using chat api like this:
```
attachment = {
       attachments: [{
        title: 'a title'
        fallback: 'a fallback'
        title_link: 'http://example.com'
       }]
     }
robot.adapter.client.web.chat.postMessage(msg.message.room, {attachment}, {as_user: true, unfurl_links: false})
```

Tried this too:
```
attachment2 = {attachments:[
         text: "Message content"
         title: "message title"
         image_url: "https://www.snipstock.com/assets/cdn/png/new/b50c79a7995782cedc741493b3c13e6b.png"
      ]}
robot.send attachment2
```
But it fails with `invalid_array_arg`
```
nhandled rejection SlackAPIError: invalid_array_arg
  at makeAPICallPromiseResolverInner (/home/ubuntu/pooja/scripts/myhubot/node_modules/@slack/client/lib/clients/client.js:156:22)
  at handleHttpResponse (/home/ubuntu/pooja/scripts/myhubot/node_modules/@slack/client/lib/clients/transports/call-transport.js:105:5)
  at handleTransportResponse (/home/ubuntu/pooja/scripts/myhubot/node_modules/@slack/client/lib/clients/transports/call-transport.js:142:19)
  at apply (/home/ubuntu/pooja/scripts/myhubot/node_modules/@slack/client/node_modules/lodash/lodash.js:483:17)
  at wrapper (/home/ubuntu/pooja/scripts/myhubot/node_modules/@slack/client/node_modules/lodash/lodash.js:5293:16)
  at Request.handleRequestTranportRes (/home/ubuntu/pooja/scripts/myhubot/node_modules/@slack/client/lib/clients/transports/request.js:20:5)
  at apply (/home/ubuntu/pooja/scripts/myhubot/node_modules/@slack/client/node_modules/lodash/lodash.js:483:17)
  at Request.wrapper [as _callback] (/home/ubuntu/pooja/scripts/myhubot/node_modules/@slack/client/node_modules/lodash/lodash.js:5293:16)
  at Request.self.callback (/home/ubuntu/pooja/scripts/myhubot/node_modules/request/request.js:187:22)
  at emitTwo (events.js:106:13)
  at Request.emit (events.js:191:7)
  at Request.<anonymous> (/home/ubuntu/pooja/scripts/myhubot/node_modules/request/request.js:1048:10)
  at emitOne (events.js:96:13)
  at Request.emit (events.js:188:7)
```
Am I missing something in syntax?

**Comment by aoberoi** [comment] 2018-01-12 10:25
@p00j4 that method takes the following arguments: `channel_id`, `text`, `options`. so your code should look something like this:

```javascript
robot.adapter.client.web.chat.postMessage(msg.message.room, "message content", {
  as_user: true,
  unfurl_links: false,
  attachments: [
    {
      title: 'a title',
      fallback: 'a fallback',
      title_link: 'http://example.com'
    }
  ]
})
```

**Comment by p00j4** [comment] 2018-01-12 10:41
ah! thanks @aoberoi the bug was with me sending "as_user" etc in different argument. Thanks for the quick help 👍

**Comment by UtpalDas6** [comment] 2018-10-23 12:39
as_user=true is not sending DM as user its still sending as bot. Please help.
