### ISSUE TITLE
msg.reply urlEscaping?

### ISSUE THREAD

**Issue by omeganon** [slackhq/hubot-slack#179] opened 2015-04-14 02:19 UTC
Hi!

I recently upgraded to the latest hubot-slack using the docs here. I've copied over my custom scripts and everything seems to be working as expected with one exception. We have a script that generates a very long URL and we send that to a channel using the http://my.long.address|shorttext convention to create a more human friendly link to click (https://api.slack.com/docs/formatting). It was working for the v2 integration but not for the latest install. The bot or adapter seems to be URL-escaping the entire string so the slack server doesn't recognize it as a | shortened url. Ex --

Code: 
                    var finalURL = signupEndpoint + "?Action=login" + "&Issuer=" + encodeURIComponent(issuer) + "&Destination=" + encodeURIComponent(destination) + "&SigninToken=" + token + "|https://my.signin.aws.amazon.com/console/read-only"
                    msg.reply(finalURL)

Result in channel (highly redacted):
 https://signin.aws.amazon.com/federation?Action=login&Issuer=https%3A%2F%2F[redacted]%2Fconsole%2F&Destination=https%3A%2F%2Fconsole.aws.amazon.com%2Fconsole%2F&SigninToken=[redacted]%7Chttps://my.signin.aws.amazon.com/console/read-only

Expectation:
working link with human visible text of 'https://my.signin.aws.amazon.com/console/read-only'

I know I'm missing something but I can't figure out what it is. I've tried various permutations (spaces around, static URL, etc) but the result is the same.

Thanks in advance!

**Comment by technicalpickles** [comment] 2015-09-27 04:07
I think this is a duplicate of https://github.com/slackhq/hubot-slack/issues/43 . I just posted a work around there (basically, you can do it with attachments).

**Comment by DEGoodmanWilson** [comment] 2016-06-29 20:32
Closed as resolved—you can't send links through the RTM API like this, as it happens. Will be even more fixed in v4.

**Closed by DEGoodmanWilson** 2016-06-29 20:32 UTC
Labels: bug, possibly fixed in hubot-slack v4
